11:19:31 - INFO - STEP: run pktvisor instance on port available with user permission
11:19:32 - INFO - STEP: run mocked data dns_ipv6_udp.pcap for this network
11:19:32 - INFO - STEP: the pktvisor container status must be running
11:19:32 - INFO - STEP: pktvisor API must be enabled
11:19:33 - ERROR - HTTPConnectionPool(host='localhost', port=44543): Max retries exceeded with url: /api/v1/policies (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c15a1a130>: Failed to establish a new connection: [Errno 111] Connection refused'))
NoneType: None
